### ISSUE TITLE
For Downloading Datasets

### ISSUE THREAD

**Issue by MeycL** [Fried-Rice-Lab/EMT#4]
Thank you so much for your wonderful work and sincerely look forward to this job being accepted. I always report a network error in the middle of downloading the provided dataset, and my download is interrupted when I get to more than 30GB, can I trouble the author to give a Baidu.com disk link? It may be a pain in the ass, but I'd appreciate it if you could.

**Comment by liozur** [comment]
Thank you for your sincere wishes.

We are uploading the processed DIV2K & DF2K dataset (processed using [extract_subimages.py](https://github.com/Fried-Rice-Lab/FriedRiceLab/blob/master/scripts/extract_subimages.py) and [create_lmdb.py](https://github.com/Fried-Rice-Lab/FriedRiceLab/blob/master/scripts/create_lmdb.py), more info can be found in BasicSR doc). Since the size of the processed dataset is much larger than its original size (which may cause download problems), you can visit the dataset's official website for the original images and process the data yourself.

We do not have any plan to upload data to the Baidu Disk.

**Comment by MeycL** [comment]
Thanks
